events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ปิดการโชว์เวอร์ชัน Nginx เพื่อความปลอดภัย (Hardening)
    server_tokens off;

    server {
        listen 80;
        server_name localhost;

        # กำหนดช่องทางบันทึก log ของ Nginx ไว้ในโฟลเดอร์เว็บเพื่อให้ฝั่ง React เรียกอ่านได้
        access_log /usr/share/nginx/html/logs/access.log;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # ปิดการบันทึก log สำหรับพอร์ตเรียกอ่านไฟล์ log เพื่อป้องกัน Loop เขียนทับไม่สิ้นสุด
        location /logs/ {
            alias /usr/share/nginx/html/logs/;
            access_log off;
            default_type text/plain;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires 0;
        }

        # เส้นทางจำลองภัยคุกคามเพื่อทดสอบ WAF Block (จะถูกบันทึกเป็น Status 403 ใน Log จริง)
        location /api/block-me {
            return 403 "Blocked by WAF security policy.";
        }

        # [เตรียมไว้ในอนาคต] ถ้าวันไหนคุณทำ Backend เสร็จ ค่อยมาเปิดตรงนี้
        # location /api/ {
        #     proxy_pass http://my_backend_servers;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}
