events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    # ประกาศรูปแบบ Log พิเศษ (ดึงข้อมูลทราฟฟิก ขนาดไฟล์ และค่าหน่วงเวลาของ Network)
    log_format network_telemetry '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" $request_time $upstream_response_time';

    upstream web_servers {
        server app-1:80;
        server app-2:80;
    }

    server {
        listen 80;
        server_name localhost;

        # บันทึกโดยใช้ Format พิเศษสำหรับวิเคราะห์ Network Telemetry
        access_log /usr/share/nginx/html/logs/access.log network_telemetry;

        location /logs/ {
            root /usr/share/nginx/html;
            access_log off;
            default_type text/plain;
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires 0;
            add_header Access-Control-Allow-Origin *;
        }

        location /api/block-me {
            access_log /usr/share/nginx/html/logs/access.log network_telemetry;
            add_header Access-Control-Allow-Origin *;
            return 403 "Blocked by WAF Policy at Load Balancer.";
        }

        location / {
            proxy_pass http://web_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header X-Upstream-Address $upstream_addr always;
            add_header X-Upstream-Response-Time $upstream_response_time always;
        }
    }
}
